version: "3.8"
services:
  web:
    build: ./apache-with-mysqli/
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./app/:/var/www/html
      - "/etc/localtime:/etc/localtime:ro"
    environment:
       OWKEY: f8ade6e21dca34d6292242d07204b3dd
       DB_HOST: db:3306
       DB_USER: root
       DB_PASS: root_password
       DB_NAME: weather_data_db
    links:
      - db
  db:
    build : ./mysql-with-structure/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: weather_data_db
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
